### ISSUE TITLE
Update TVL and Volume queries

### ISSUE THREAD

**Issue by tiagofilipenunes** [bancorprotocol/carbon-backend#26]
Update TVL and Volume queries to include pair information. The new queries are in the last comment.

**Comment by ashachaf** [comment]
@tiagofilipenunes worth adding the following
- [ ] start_time
- [ ] limit
currently, this endpoint return ALL daily volume from genesis for ALL tokens.
the file size is getting too large and will continue growing to sizes where it cannot be managed.

**Comment by tiagofilipenunes** [comment]
New queries:

[Queries.zip](https://github.com/user-attachments/files/16638152/Queries.zip)

**Comment by tiagofilipenunes** [comment]
# Queries v2

[Queries v2.zip](https://github.com/user-attachments/files/16715230/Queries.v2.zip)

The tvl table only keeps the fresh data. Getting the TVL by symbol or TVL by pairName will get the data from TVL, add the latest strategy, forward active strategies daily, get USD prices, and then limit by date and group by symbol or pairName.

Getting the TVL by symbol or pairName might take a while the first time, so it's worth caching with a key that truncates start and end date so it runs once a day only.

The analytics.md file describes the updating and retrieval process:

## TVL

### Updater
Input: 
- startBlock - the last updated block for the "tvl" table

Process
1. Get all StrategyCreated, StrategyUpdated, StrategyDeleted events. From these, separate new_events from prior_events via the latest updated block (startBlock).
2. Add to the latest StrategyCreated and StrategyUpdated events for each strategy so there is TVL information for all active strategies at the start of the table.
3. Extract y from both orders and divide it by 10**decimals to get the tvl.

### Retrieve from updater
Input: 
- startDate - date from which to show data. This date will be moved back to 00:00UTC. Example: "22-08-2024 18:03:58" -> "22-08-2024 00:00:00"
- endDate - that will be moved forward to 00:00UTC. Ex if "22-08-2024 18:03:58" -> "23-08-2024 00:00:00"

Process
1. Get all strategy information from the updated tvl query, from the latest updated block (startBlock).
2. Add latest TVL information for each missing non-deleted strategy.
3. Propagate strategy information so that there is one row per day with TVL information for each strategy.
4. Add USD prices and calculate USD TVL.


## Fees/volume

### Updater
Input: 
- startBlock - the last updated block for the "volume" table
1. Get all TokenTraded events from the latest updated block (startBlock).
2. Get the fee token from byTargetAmount column.
3. Add USD prices and calculate trading fee and volume amount in USD prices.

### Retrieve from updater
Input: 
- startDate - date from which to show data. This date will be moved back to 00:00UTC. Example: "22-08-2024 18:03:58" -> "22-08-2024 00:00:00"
- endDate - that will be moved forward to 00:00UTC. Ex if "22-08-2024 18:03:58" -> "23-08-2024 00:00:00"

Process:
1. Get information from "volume" table and add over symbol or over pairName for each evt_day.
