### ISSUE TITLE
Empty param - fall back to default preset

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-backend#45]
When appending a param into the API endpoint call with no values
```
example: 
https://multi.carbondefi.xyz/v1/sei/activity/meta?actions=
```
current behavior:
return an error indicating a value is required
```{"message":["each value in actions must be one of the following values: sell, buy, create, deposit, withdraw, transfer, edit, delete, pause"],"error":"Bad Request","statusCode":400}```

updated behavior:
ignore the indicated param and use the default setting as if it was not passed at all
```
example:
call this endpoint: https://multi.carbondefi.xyz/v1/sei/activity/meta?actions=
since _actions_ has no values, ignore it and assume the call was for this endpoing: https://multi.carbondefi.xyz/v1/sei/activity/meta?
```

**Comment by yarivbancor** [comment]
@ashachaf 
omitting the empty actions= will yield the default behavior.
swagger seems to remove it from the url when clearing out the action.
i think this is a non issue?
