### ISSUE TITLE
Missing Database Schema Documentation

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/carbon-backend#90]
There is no visible documentation or ERD of the database structure, which could make it difficult for new developers to understand data flows.

**Comment by yarivbancor** [comment]
please note every table in the db is represented by a very detailed entity file.
any change/addition to the db is done by modifiying these files, and migrations are generated automatically with npm run scripts

**Comment by zavelevsky** [comment]
> please note every table in the db is represented by a very detailed entity file. any change/addition to the db is done by modifiying these files, and migrations are generated automatically with npm run scripts

While this is true, I'd claim that a higher-level database schema overview is still valuable. An ERD or similar schema documentation provides an accessible, visual snapshot of the relationships between tables, which is particularly helpful for:

- Onboarding and Collaboration (New team members or external collaborators / licensees) - not  needing to go through each entity file in detail.

- System Design Discussions: A visual schema is useful in planning and architectural discussions.

- Database Management: with more people involved, a schema overview helps ensure everyone understands the relationships and data flow, reducing the chance of misinterpretation or errors during maintenance.
