### ISSUE TITLE
fallback market price resources

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/carbon-backend#94]
Main goal - have maximum coverage for token prices
Secondary goal - use the "most consensus" prices for each token

Design  work is required.

Here's a suggested approach:
- We want to be able to define multiple sources for market rates, off chain and, potentially, on chain
- sources will be prioritized (configurable) per chain
- for each token we will try to fetch prices from the first resource and, if not available, move to the next
- it's an "all or nothing" approach per each token. So, for example, if we have historical quotes for a token we take the entire history - even if there are gaps. We don't fill gaps in history using another resource because we are worried that the variance will make it too weird.
- We need to offer a way, possibly by configuration, to address the limitation above by specifying exceptions, e.g. - for TKN-A never get historical quotes from Provider X because we know it's bad. 
- This design should take into account the possibility that we'll be harvesting on-chain prices to be used as yet another resource.

For full context: It should be noted and taken into account that this should go hand in hand with the effort of finding and cultivating a reliable 3rd party API that will get prices from Carbon and list them, to support our business offering.
In such case we'll likely need to expose an API to support this.

**Comment by yarivbancor** [comment]
closed by #97
